// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCThl7gOtYjwJBuv-3jqHeBr9Gk-8pfTVY',
    appId: '1:998511026007:web:0ff097539262be4c036812',
    messagingSenderId: '998511026007',
    projectId: 'app-towhere',
    authDomain: 'app-towhere.firebaseapp.com',
    storageBucket: 'app-towhere.firebasestorage.app',
    measurementId: 'G-LZWWRE8WBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWDSQiwgXqfHc-MhDKfmwHRe-bbt3mQA',
    appId: '1:998511026007:android:8c4e57d135fc39da036812',
    messagingSenderId: '998511026007',
    projectId: 'app-towhere',
    storageBucket: 'app-towhere.firebasestorage.app',
  );

}